
'use server';

/**
 * @fileOverview Defines Genkit tools for creating manga entities (Project, Chapter, Scene, Panel, Dialogue, Character) in the data store.
 * These tools allow the AI to add new structured elements based on prompts or instructions.
 */

import ai from '@/ai/ai-instance';
import { z } from 'genkit';
// Import data service functions
import {
    createProject as createProjectService,
    createChapter as createChapterService,
    createScene as createSceneService,
    createPanel as createPanelService,
    createPanelDialogue as createPanelDialogueService,
    createCharacter as createCharacterService,
    // Import context fetchers if needed for validation (e.g., ensure parent exists)
    getProject as getProjectForContext,
    getChapterForContext,
    getSceneForContext,
    getPanelForContext,
    getAllCharacters, // Needed for assigning speaker/characters by name
} from '@/services/data-service';
// Import Zod schemas for input validation and defining structure
import { mangaProjectSchema, chapterSchema, sceneSchema, panelSchema, panelDialogueSchema, characterSchema } from '@/types/schemas';
import type { Scene, Panel, PanelDialogue, Character } from '@/types/entities'; // Import types for context helpers

// --- Helper to get projectId for context (if not directly provided) ---
// Tries to infer project ID from parent entities.
async function getProjectIdForContext(context: { chapterId?: string, sceneId?: string, panelId?: string, characterId?: string }): Promise<string | undefined> {
     if (context.chapterId) {
         const chapter = await getChapterForContext(context.chapterId);
         return chapter?.mangaProjectId;
     }
     if (context.sceneId) {
         const scene = await getSceneForContext(context.sceneId);
         if (scene) {
            const chapter = await getChapterForContext(scene.chapterId);
            return chapter?.mangaProjectId;
         }
     }
      if (context.panelId) {
         const panel = await getPanelForContext(context.panelId);
         if (panel) {
            const scene = await getSceneForContext(panel.sceneId);
             if (scene) {
                const chapter = await getChapterForContext(scene.chapterId);
                return chapter?.mangaProjectId;
             }
         }
     }
       if (context.characterId) {
         const character = await getCharacterForContext(context.characterId);
         return character?.mangaProjectId;
     }
    console.warn("Could not determine projectId from context in getProjectIdForContext helper.");
    return undefined;
}


// --- Tool: Create Manga Project ---
// Note: In this app, the project is usually pre-existing (the default one).
// This tool might be less used but is included for completeness.
export const createProjectTool = ai.defineTool({
    name: 'createProject',
    description: 'Creates a new manga project with initial details.',
    // Use the Zod schema, omitting fields generated by the backend (id, dates, relations)
    inputSchema: mangaProjectSchema.omit({ id: true, createdAt: true, updatedAt: true, chapters: true, characters: true, viewCount: true, likeCount: true, published: true })
        .describe("The initial data for the new manga project."),
    outputSchema: z.string().describe('The ID of the newly created project.'),
}, async (input) => {
    console.log("Tool: Creating project", input);
    try {
        // Call the data service function
        const project = await createProjectService({
            ...input,
            // Ensure required fields have defaults if not in schema (e.g., status)
             status: input.status ?? 'draft',
             // Handle potential JSON string fields from schema if needed
             worldDetails: typeof input.worldDetails === 'string' ? JSON.parse(input.worldDetails) : input.worldDetails,
             locations: typeof input.locations === 'string' ? JSON.parse(input.locations) : input.locations,
             plotStructure: typeof input.plotStructure === 'string' ? JSON.parse(input.plotStructure) : input.plotStructure,
             keyEvents: typeof input.keyEvents === 'string' ? JSON.parse(input.keyEvents) : input.keyEvents,
             themes: typeof input.themes === 'string' ? input.themes.split(',').map(t => t.trim()) : input.themes,
             motifs: typeof input.motifs === 'string' ? input.motifs.split(',').map(t => t.trim()) : input.motifs,
             symbols: typeof input.symbols === 'string' ? input.symbols.split(',').map(t => t.trim()) : input.symbols,
             tags: typeof input.tags === 'string' ? input.tags.split(',').map(t => t.trim()) : input.tags,
             // Add defaults for missing non-optional fields if any
             title: input.title, // Already required by schema
        });
        return project.id;
    } catch (error: any) {
        console.error("Error in createProjectTool:", error.message);
        // Consider returning a more informative error or null
        throw new Error(`Failed to create project: ${error.message}`);
    }
});


// --- Tool: Create Chapter ---
export const createChapterTool = ai.defineTool({
  name: 'createChapter',
  description: 'Creates a new chapter within a specified manga project.',
  // Input schema based on Chapter entity, requires projectId, omits generated fields
  inputSchema: chapterSchema.omit({ id: true, createdAt: true, updatedAt: true, scenes: true })
    .extend({
        mangaProjectId: z.string().describe("The ID of the parent project."),
        // Make description optional for creation if needed
         summary: z.string().optional().describe("A brief summary of the chapter."),
         // Ensure AI provides basic required fields
         title: z.string().describe("The title of the chapter."),
         chapterNumber: z.number().int().positive().describe("The chapter number."),
         keyCharacters: z.array(z.string()).optional().describe("Names of key characters appearing in this chapter."),
    })
    .describe("Data for the new chapter, including the parent project ID."),
  outputSchema: z.string().describe('The ID of the newly created chapter.'),
}, async (input) => {
  console.log("Tool: Creating chapter for project", input.mangaProjectId, input);
  try {
      // Ensure project exists (optional validation)
       const projectExists = await getProjectForContext(input.mangaProjectId);
       if (!projectExists) {
           throw new Error(`Parent project ${input.mangaProjectId} not found.`);
       }

      const chapter = await createChapterService({
          ...input,
          // Convert comma-separated strings back to arrays if needed
          keyCharacters: Array.isArray(input.keyCharacters) ? input.keyCharacters : (typeof input.keyCharacters === 'string' ? input.keyCharacters.split(',').map(t=>t.trim()) : []),
          // Add defaults for missing non-optional fields if any
          isAiGenerated: input.isAiGenerated ?? true,
          isPublished: input.isPublished ?? false,
          viewCount: input.viewCount ?? 0,
      });
      return chapter.id;
  } catch (error: any) {
      console.error("Error in createChapterTool:", error.message);
      throw new Error(`Failed to create chapter: ${error.message}`);
  }
});


// --- Tool: Create Scene ---
export const createSceneTool = ai.defineTool({
  name: 'createScene',
  description: 'Creates a new scene within a specific chapter.',
  // Input schema based on Scene entity, requires chapterId, omits generated fields
  inputSchema: sceneSchema.omit({ id: true, createdAt: true, updatedAt: true, panels: true })
    .extend({
        chapterId: z.string().describe("The ID of the parent chapter."),
         // Ensure AI provides basic required fields
         title: z.string().describe("A descriptive title for the scene."),
         order: z.number().int().nonnegative().describe("The sequential order of the scene within the chapter."),
         // Scene context should be structured object
         sceneContext: z.object({
             setting: z.string().describe('Where and when the scene takes place (e.g., "Rainy alley at night").'),
             mood: z.string().describe('The emotional atmosphere (e.g., "Tense", "Comedic", "Mysterious").'),
             presentCharacters: z.array(z.string()).describe('Names of characters actively involved in the scene.'),
             timeOfDay: z.string().optional().describe('Specific time if relevant (e.g., "Dawn", "Midnight").'),
             weather: z.string().optional().describe('Weather conditions if relevant (e.g., "Snowing", "Sunny").'),
         }).describe('Contextual details defining the scene environment and participants.'),
         dialogueOutline: z.string().optional().describe("A high-level outline or summary of the dialogue that occurs in this scene."),
    })
    .describe("Data for the new scene, including the parent chapter ID."),
  outputSchema: z.string().describe('The ID of the newly created scene.'),
}, async (input) => {
   console.log("Tool: Creating scene for chapter", input.chapterId, input);
   try {
        // Ensure chapter exists (optional validation)
        const chapterExists = await getChapterForContext(input.chapterId);
        if (!chapterExists) {
            throw new Error(`Parent chapter ${input.chapterId} not found.`);
        }

       // Parse sceneContext if it's a string
       let parsedSceneContext = input.sceneContext;
       if (typeof input.sceneContext === 'string') {
           try {
               parsedSceneContext = JSON.parse(input.sceneContext);
           } catch (e) { throw new Error("Invalid JSON string provided for sceneContext."); }
       }

       const scene = await createSceneService({
           ...input,
           sceneContext: parsedSceneContext, // Use parsed object
           isAiGenerated: input.isAiGenerated ?? true,
       });
       return scene.id;
   } catch (error: any) {
       console.error("Error in createSceneTool:", error.message);
       throw new Error(`Failed to create scene: ${error.message}`);
   }
});

// --- Tool: Create Panel ---
export const createPanelTool = ai.defineTool({
    name: 'createPanel',
    description: 'Creates a new panel within a specific scene. Panels depict visual moments and actions.',
    // Input schema based on Panel entity, requires sceneId, omits generated fields
    inputSchema: panelSchema.omit({ id: true, createdAt: true, updatedAt: true, dialogues: true, characters: true, characterIds: true /* We handle IDs separately */ })
        .extend({
            sceneId: z.string().describe("The ID of the parent scene."),
            // Ensure AI provides basic required fields
            order: z.number().int().nonnegative().describe("The sequential order of the panel within the scene."),
            // Panel context should be structured object
             panelContext: z.object({
                action: z.string().describe('The primary action or event depicted (e.g., "Character throws punch").'),
                pose: z.string().optional().describe('General pose or composition description.'),
                characterPoses: z.array(z.object({
                    characterName: z.string().describe("Name of the character."),
                    pose: z.string().describe("Specific pose (e.g., 'crouching', 'arms crossed')."),
                    expression: z.string().optional().describe("Facial expression (e.g., 'smiling', 'angry')."),
                })).optional().describe('Pose/expression for each character visible.'),
                emotion: z.string().optional().describe('Dominant emotion conveyed visually.'),
                cameraAngle: z.enum(['close-up', 'medium', 'wide', "bird's eye", 'low angle']).optional(),
                shotType: z.enum(['action', 'reaction', 'establishing', 'detail']).optional(),
                backgroundDescription: z.string().optional().describe("Background elements."),
                lighting: z.string().describe('Lighting description (e.g., "Dramatic shadows").'),
                effects: z.array(z.string()).optional().describe('Visual effects (e.g., speed lines, impact stars).'),
                dramaticPurpose: z.string().describe('Narrative goal (e.g., "Reveal surprise").'),
                narrativePosition: z.string().describe('Where it fits (e.g., "Start of action").'),
            }).describe('Detailed visual and narrative context for the panel.'),
             // Accept character *names* for linking
            characterNames: z.array(z.string()).optional().describe('Names of characters present in this panel (for linking).'),
             aiPrompt: z.string().optional().describe('Concise prompt for AI image generation, summarizing visuals.'),
        })
        .describe("Data for the new panel, including parent scene ID and character names."),
    outputSchema: z.string().describe('The ID of the created panel.'),
}, async (input) => {
     console.log("Tool: Creating panel for scene", input.sceneId, input);
     try {
          // Ensure scene exists (optional validation)
        const sceneExists = await getSceneForContext(input.sceneId);
        if (!sceneExists) {
            throw new Error(`Parent scene ${input.sceneId} not found.`);
        }

         // Resolve character names to IDs
         let characterIds: string[] = [];
         const projectId = await getProjectIdForContext({ sceneId: input.sceneId });
         if (input.characterNames && input.characterNames.length > 0 && projectId) {
             const charactersInProject = await getAllCharacters(projectId);
             characterIds = input.characterNames
                 .map(name => charactersInProject.find(c => c.name.toLowerCase() === name.toLowerCase())?.id)
                 .filter((id): id is string => !!id); // Filter out undefined/null IDs
         } else if (input.characterNames && !projectId) {
             console.warn("Cannot resolve character names to IDs without project context in createPanelTool.");
         }

          // Parse panelContext if it's a string
         let parsedPanelContext = input.panelContext;
         if (typeof input.panelContext === 'string') {
             try {
                 parsedPanelContext = JSON.parse(input.panelContext);
             } catch (e) { throw new Error("Invalid JSON string provided for panelContext."); }
         }

         const panel = await createPanelService({
             ...input,
             panelContext: parsedPanelContext, // Use parsed object
             characterIds: characterIds, // Pass resolved IDs
             isAiGenerated: input.isAiGenerated ?? true,
         });
         return panel.id;
     } catch (error: any) {
         console.error("Error in createPanelTool:", error.message);
         throw new Error(`Failed to create panel: ${error.message}`);
     }
});


// --- Tool: Create Panel Dialogue ---
export const createPanelDialogueTool = ai.defineTool({
    name: 'createPanelDialogue',
    description: 'Creates a dialogue entry (speech bubble, caption) associated with a specific panel.',
    // Input schema based on PanelDialogue entity, requires panelId, omits generated fields
    inputSchema: panelDialogueSchema.omit({ id: true, createdAt: true, updatedAt: true, speaker: true, speakerId: true /* Handle speaker by name */ })
        .extend({
            panelId: z.string().describe("The ID of the parent panel."),
             // Ensure AI provides basic required fields
             order: z.number().int().nonnegative().describe('Order of this dialogue within the panel.'),
             content: z.string().describe('The exact dialogue text or caption.'),
             // Accept speaker name for linking
             speakerName: z.string().optional().describe('Name of the character speaking (if applicable). Tool will try to find ID.'),
             // Style context should be structured object
              style: z.object({
                  bubbleType: z.enum(['normal', 'thought', 'scream', 'whisper', 'narration']).optional().describe("Visual style of the bubble/caption."),
              }).optional().describe("Stylistic hints for the dialogue."),
             emotion: z.string().optional().describe("Emotion conveyed by the dialogue delivery."),
             subtextNote: z.string().optional().describe("Underlying meaning or director's note."),
        })
        .describe("Data for the new dialogue, including parent panel ID and speaker name."),
    outputSchema: z.string().describe('The ID of the created dialogue entry.'),
}, async (input) => {
    console.log("Tool: Creating dialogue for panel", input.panelId, input);
    try {
         // Ensure panel exists (optional validation)
        const panelExists = await getPanelForContext(input.panelId);
        if (!panelExists) {
            throw new Error(`Parent panel ${input.panelId} not found.`);
        }

         // Resolve speaker name to ID
         let speakerId: string | undefined | null = null;
         const projectId = await getProjectIdForContext({ panelId: input.panelId });
         if (input.speakerName && projectId) {
              const characters = await getAllCharacters(projectId);
              const found = characters.find(c => c.name.toLowerCase() === input.speakerName?.toLowerCase());
              speakerId = found?.id;
              if (!speakerId) {
                  console.warn(`Could not find character ID for speaker: ${input.speakerName} in project ${projectId}`);
              }
         } else if (input.speakerName && !projectId) {
              console.warn("Cannot resolve speaker name to ID without project context in createPanelDialogueTool.");
         }

         // Parse style if it's a string
          let parsedStyle = input.style;
          if (typeof input.style === 'string') {
              try {
                  parsedStyle = JSON.parse(input.style);
              } catch (e) { console.warn("Invalid JSON string provided for dialogue style. Using default."); parsedStyle = undefined; }
          }

         const dialogue = await createPanelDialogueService({
             ...input,
             style: parsedStyle, // Use parsed object
             speakerId: speakerId, // Pass resolved ID or null
             isAiGenerated: input.isAiGenerated ?? true,
         });
         return dialogue.id;
    } catch (error: any) {
        console.error("Error in createPanelDialogueTool:", error.message);
        throw new Error(`Failed to create dialogue: ${error.message}`);
    }
});


// --- Tool: Create Character ---
export const createCharacterTool = ai.defineTool({
    name: 'createCharacter',
    description: 'Creates a new character profile within the specified project.',
    // Input schema based on Character entity, requires projectId, omits generated fields
    inputSchema: characterSchema.omit({ id: true, createdAt: true, updatedAt: true })
        .extend({
            mangaProjectId: z.string().describe("The project the character belongs to."),
            // Ensure AI provides basic required fields
            name: z.string().describe("The character's name."),
            // Make other fields optional for initial creation
             briefDescription: z.string().optional().describe("A short description."),
             role: z.enum(['protagonist', 'antagonist', 'supporting', 'minor']).optional(),
             imgUrl: z.string().url().optional().describe("URL to an existing image for the character (optional)."),
        })
        .describe("Data for the new character, including the parent project ID."),
    outputSchema: z.string().describe("The ID of the created character."),
}, async (input) => {
    console.log("Tool: Creating character for project", input.mangaProjectId, input);
    try {
         // Ensure project exists (optional validation)
        const projectExists = await getProjectForContext(input.mangaProjectId);
        if (!projectExists) {
            throw new Error(`Parent project ${input.mangaProjectId} not found.`);
        }

        const character = await createCharacterService({
            ...input,
            // Handle potential JSON string fields from schema if needed
            bodyAttributes: typeof input.bodyAttributes === 'string' ? JSON.parse(input.bodyAttributes) : input.bodyAttributes,
            facialAttributes: typeof input.facialAttributes === 'string' ? JSON.parse(input.facialAttributes) : input.facialAttributes,
            hairAttributes: typeof input.hairAttributes === 'string' ? JSON.parse(input.hairAttributes) : input.hairAttributes,
            expressionStyle: typeof input.expressionStyle === 'string' ? JSON.parse(input.expressionStyle) : input.expressionStyle,
            style: typeof input.style === 'string' ? JSON.parse(input.style) : input.style,
            styleGuide: typeof input.styleGuide === 'string' ? JSON.parse(input.styleGuide) : input.styleGuide,
            visualIdentityAnchors: typeof input.visualIdentityAnchors === 'string' ? JSON.parse(input.visualIdentityAnchors) : input.visualIdentityAnchors,
            expressionImages: typeof input.expressionImages === 'string' ? JSON.parse(input.expressionImages) : input.expressionImages,
            // Handle simple arrays
            distinctiveFeatures: typeof input.distinctiveFeatures === 'string' ? input.distinctiveFeatures.split(',').map(t=>t.trim()) : input.distinctiveFeatures,
            physicalMannerisms: typeof input.physicalMannerisms === 'string' ? input.physicalMannerisms.split(',').map(t=>t.trim()) : input.physicalMannerisms,
            referenceImageUrls: typeof input.referenceImageUrls === 'string' ? input.referenceImageUrls.split(',').map(t=>t.trim()) : input.referenceImageUrls,
            traits: typeof input.traits === 'string' ? input.traits.split(',').map(t=>t.trim()) : input.traits,
            arcs: typeof input.arcs === 'string' ? input.arcs.split(',').map(t=>t.trim()) : input.arcs,
            isAiGenerated: input.isAiGenerated ?? true,
        });
        return character.id;
    } catch (error: any) {
        console.error("Error in createCharacterTool:", error.message);
        throw new Error(`Failed to create character: ${error.message}`);
    }
});
