"use client";
import { CharacterCard } from "@/components/CharacterCard";
import React, { useRef, useState } from "react";

type CardType = {
  name: string;
  attribute: string;
  level: number;
  imageUrl: string;
  type: string;
  race: string;
  description: string;
  atk: number;
  def: number;
  rarity: "Common" | "Rare" | "Ultra Rare" | "Secret Rare";
  lore: string;
};

const defaultCard: CardType = {
  name: "Custom Card Name",
  attribute: "Light",
  level: 4,
  imageUrl: "/images/hero-bg.png",
  type: "Warrior",
  race: "Human",
  description: "A custom card description.",
  atk: 1500,
  def: 1200,
  rarity: "Rare",
  lore: "This is a custom card lore.",
};

const rarityOptions = ["Common", "Rare", "Ultra Rare", "Secret Rare"];
const attributeOptions = [
  "Light",
  "Dark",
  "Fire",
  "Water",
  "Earth",
  "Wind",
  "Divine",
];

export default function CardDesignerPage() {
  const [mode, setMode] = useState<"ai" | "manual">("manual");
  const [card, setCard] = useState({ ...defaultCard });
  const [aiPrompt, setAiPrompt] = useState("");
  const [collection, setCollection] = useState<any[]>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("cardCollection");
      return saved ? JSON.parse(saved) : [];
    }
    return [];
  });
  const [history, setHistory] = useState<any[]>([]);
  const [future, setFuture] = useState<any[]>([]);
  const [showCollection, setShowCollection] = useState(false);
  const [flipped, setFlipped] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  function handleChange(
    e: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >
  ) {
    setHistory((h) => [...h, card]);
    setFuture([]);
    setCard({ ...card, [e.target.name]: e.target.value });
  }

  function handleNumberChange(e: React.ChangeEvent<HTMLInputElement>) {
    setHistory((h) => [...h, card]);
    setFuture([]);
    setCard({ ...card, [e.target.name]: Number(e.target.value) });
  }

  function handleAIGenerate() {
    setHistory((h) => [...h, card]);
    setFuture([]);
    setCard({
      name: "AI Dragon",
      attribute: "Fire",
      level: 7,
      imageUrl: "/images/hero-bg.png",
      type: "Dragon",
      race: "AI",
      description: "A mighty dragon generated by AI, with blazing power.",
      atk: 2700,
      def: 2100,
      lore: "Born from code and fire, this dragon rules the digital skies.",
      rarity: "Ultra Rare",
    });
  }

  function handleSave() {
    const newCollection = [...collection, card];
    setCollection(newCollection);
    localStorage.setItem("cardCollection", JSON.stringify(newCollection));
    alert("Card saved to your collection!");
  }

  function handleExport() {
    const dataStr =
      "data:text/json;charset=utf-8," +
      encodeURIComponent(JSON.stringify(card, null, 2));
    const dlAnchor = document.createElement("a");
    dlAnchor.setAttribute("href", dataStr);
    dlAnchor.setAttribute(
      "download",
      `${card.name.replace(/\s+/g, "_")}_card.json`
    );
    document.body.appendChild(dlAnchor);
    dlAnchor.click();
    dlAnchor.remove();
  }

  function handleImport(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const imported = JSON.parse(event.target?.result as string);
        setCard(imported);
        alert("Card imported!");
      } catch {
        alert("Invalid card file.");
      }
    };
    reader.readAsText(file);
  }

  function handleRandom() {
    const random = {
      name: "Random Card " + Math.floor(Math.random() * 1000),
      attribute:
        attributeOptions[Math.floor(Math.random() * attributeOptions.length)],
      level: Math.floor(Math.random() * 12) + 1,
      imageUrl: "/images/hero-bg.png",
      type: ["Warrior", "Dragon", "Spellcaster", "Beast", "Machine"][
        Math.floor(Math.random() * 5)
      ],
      race: ["Human", "Elf", "AI", "Demon", "Spirit"][
        Math.floor(Math.random() * 5)
      ],
      description: "A mysterious card with unpredictable power.",
      atk: Math.floor(Math.random() * 4000),
      def: Math.floor(Math.random() * 4000),
      rarity: rarityOptions[
        Math.floor(Math.random() * rarityOptions.length)
      ] as CardType["rarity"],
      lore: "Randomly generated lore.",
    };
    setHistory((h) => [...h, card]);
    setFuture([]);
    setCard(random);
  }

  function handleUndo() {
    if (history.length === 0) return;
    setFuture((f) => [card, ...f]);
    setCard(history[history.length - 1]);
    setHistory((h) => h.slice(0, -1));
  }

  function handleRedo() {
    if (future.length === 0) return;
    setHistory((h) => [...h, card]);
    setCard(future[0]);
    setFuture((f) => f.slice(1));
  }

  function handleShare() {
    navigator.clipboard.writeText(JSON.stringify(card, null, 2));
    alert("Card JSON copied to clipboard!");
  }

  function handleExportImage() {
    const cardNode = document.getElementById("card-preview");
    if (!cardNode) return alert("Card preview not found");
    import("html2canvas").then((html2canvas) => {
      html2canvas.default(cardNode).then((canvas) => {
        const url = canvas.toDataURL("image/png");
        const link = document.createElement("a");
        link.download = `${card.name.replace(/\s+/g, "_")}_card.png`;
        link.href = url;
        link.click();
      });
    });
  }

  return (
    <main className="min-h-screen flex flex-col items-center bg-gradient-to-br from-gray-900 via-gray-800 to-black p-4">
      <h1 className="text-3xl font-bold mb-6 text-red-500 drop-shadow-lg tracking-widest font-serif uppercase">
        Card Designer
      </h1>
      <div className="mb-6 flex gap-4">
        <button
          className={`px-4 py-2 rounded font-bold border-2 transition-colors ${
            mode === "ai"
              ? "bg-red-500 text-white border-red-500"
              : "bg-gray-800 text-white border-red-700"
          }`}
          onClick={() => setMode("ai")}
        >
          AI Designer
        </button>
        <button
          className={`px-4 py-2 rounded font-bold border-2 transition-colors ${
            mode === "manual"
              ? "bg-red-500 text-white border-red-500"
              : "bg-gray-800 text-white border-red-700"
          }`}
          onClick={() => setMode("manual")}
        >
          Manual Designer
        </button>
      </div>
      <div className="flex flex-col md:flex-row gap-8 w-full max-w-5xl items-start">
        <div className="flex-1 w-full max-w-md">
          {mode === "ai" ? (
            <div className="bg-gray-900 border border-red-700 rounded-lg p-4 mb-4">
              <label className="block text-white font-semibold mb-2">
                Describe your card idea:
              </label>
              <textarea
                className="w-full rounded p-2 bg-gray-800 text-white border border-red-700 mb-2"
                rows={3}
                value={aiPrompt}
                onChange={(e) => setAiPrompt(e.target.value)}
                placeholder="e.g. A legendary water mage with healing powers"
              />
              <button
                className="mt-2 px-4 py-2 bg-red-500 text-white font-bold rounded shadow hover:bg-red-400"
                onClick={handleAIGenerate}
              >
                Generate Card
              </button>
            </div>
          ) : (
            <form className="bg-gray-900 border border-red-700 rounded-lg p-4 grid grid-cols-1 gap-3">
              <label className="text-white font-semibold">
                Name
                <input
                  name="name"
                  className="w-full rounded p-2 bg-gray-800 text-white border border-red-700"
                  value={card.name}
                  onChange={handleChange}
                  maxLength={32}
                />
              </label>
              <label className="text-white font-semibold">
                Attribute
                <select
                  name="attribute"
                  className="w-full rounded p-2 bg-gray-800 text-white border border-red-700"
                  value={card.attribute}
                  onChange={handleChange}
                >
                  {attributeOptions.map((opt) => (
                    <option key={opt}>{opt}</option>
                  ))}
                </select>
              </label>
              <label className="text-white font-semibold">
                Level
                <input
                  name="level"
                  type="number"
                  min={1}
                  max={12}
                  className="w-full rounded p-2 bg-gray-800 text-white border border-red-700"
                  value={card.level}
                  onChange={handleNumberChange}
                />
              </label>
              <label className="text-white font-semibold">
                Image URL
                <input
                  name="imageUrl"
                  className="w-full rounded p-2 bg-gray-800 text-white border border-red-700"
                  value={card.imageUrl}
                  onChange={handleChange}
                />
              </label>
              <label className="text-white font-semibold">
                Type
                <input
                  name="type"
                  className="w-full rounded p-2 bg-gray-800 text-white border border-red-700"
                  value={card.type}
                  onChange={handleChange}
                />
              </label>
              <label className="text-white font-semibold">
                Race
                <input
                  name="race"
                  className="w-full rounded p-2 bg-gray-800 text-white border border-red-700"
                  value={card.race}
                  onChange={handleChange}
                />
              </label>
              <label className="text-white font-semibold">
                Description
                <textarea
                  name="description"
                  className="w-full rounded p-2 bg-gray-800 text-white border border-red-700"
                  rows={3}
                  value={card.description}
                  onChange={handleChange}
                  maxLength={300}
                />
              </label>
              <label className="text-white font-semibold">
                ATK
                <input
                  name="atk"
                  type="number"
                  min={0}
                  max={9999}
                  className="w-full rounded p-2 bg-gray-800 text-white border border-red-700"
                  value={card.atk}
                  onChange={handleNumberChange}
                />
              </label>
              <label className="text-white font-semibold">
                DEF
                <input
                  name="def"
                  type="number"
                  min={0}
                  max={9999}
                  className="w-full rounded p-2 bg-gray-800 text-white border border-red-700"
                  value={card.def}
                  onChange={handleNumberChange}
                />
              </label>
              <label className="text-white font-semibold">
                Rarity
                <select
                  name="rarity"
                  className="w-full rounded p-2 bg-gray-800 text-white border border-red-700"
                  value={card.rarity}
                  onChange={handleChange}
                >
                  {rarityOptions.map((opt) => (
                    <option key={opt}>{opt}</option>
                  ))}
                </select>
              </label>
              <label className="text-yellow-200 font-semibold">
                Lore
                <textarea
                  name="lore"
                  className="w-full rounded p-2 bg-gray-800 text-yellow-100 border border-yellow-700"
                  rows={2}
                  value={card.lore}
                  onChange={handleChange}
                  maxLength={120}
                />
              </label>
            </form>
          )}
        </div>
        <div className="flex-1 flex flex-col items-center gap-4">
          <div className="flex gap-2 flex-wrap mb-2">
            <button
              className="px-3 py-1 bg-red-500 text-white font-bold rounded shadow hover:bg-red-400 border border-red-700"
              onClick={handleSave}
              type="button"
            >
              Save to Collection
            </button>
            <button
              className="px-3 py-1 bg-red-500 text-white font-bold rounded shadow hover:bg-red-400 border border-red-700"
              onClick={handleExportImage}
              type="button"
            >
              Export as Image
            </button>
            <button
              className="px-3 py-1 bg-red-500 text-white font-bold rounded shadow hover:bg-red-400 border border-red-700"
              onClick={handleRandom}
              type="button"
            >
              Random Card
            </button>
            <button
              className="px-3 py-1 bg-red-500 text-white font-bold rounded shadow hover:bg-red-400 border border-red-700"
              onClick={handleShare}
              type="button"
            >
              Share JSON
            </button>
            <button
              className="px-3 py-1 bg-red-500 text-white font-bold rounded shadow hover:bg-red-400 border border-red-700"
              onClick={handleExport}
              type="button"
            >
              Export JSON
            </button>
            <button
              className="px-3 py-1 bg-red-500 text-white font-bold rounded shadow hover:bg-red-400 border border-red-700"
              onClick={() => fileInputRef.current?.click()}
              type="button"
            >
              Import JSON
            </button>
            <input
              ref={fileInputRef}
              type="file"
              accept="application/json"
              className="hidden"
              onChange={handleImport}
            />
            <button
              className="px-3 py-1 bg-red-500 text-white font-bold rounded shadow hover:bg-red-400 border border-red-700"
              onClick={handleUndo}
              type="button"
              disabled={history.length === 0}
            >
              Undo
            </button>
            <button
              className="px-3 py-1 bg-red-500 text-white font-bold rounded shadow hover:bg-red-400 border border-red-700"
              onClick={handleRedo}
              type="button"
              disabled={future.length === 0}
            >
              Redo
            </button>
            <button
              className="px-3 py-1 bg-red-500 text-white font-bold rounded shadow hover:bg-red-400 border border-red-700"
              onClick={() => setFlipped((f) => !f)}
              type="button"
            >
              {flipped ? "Show Front" : "Flip Card"}
            </button>
            <button
              className="px-3 py-1 bg-red-500 text-white font-bold rounded shadow hover:bg-red-400 border border-red-700"
              onClick={() => setShowCollection((v) => !v)}
              type="button"
            >
              {showCollection ? "Hide Collection" : "View Collection"}
            </button>
          </div>
          <div
            id="card-preview"
            className={
              flipped
                ? "[transform:rotateY(180deg)] transition-transform duration-500"
                : "transition-transform duration-500"
            }
            style={{ perspective: 1000 }}
          >
            <CharacterCard {...card} showRarityLabel />
            {flipped && (
              <div
                className="absolute top-0 left-0 w-full h-full flex flex-col items-center justify-center bg-gradient-to-br from-gray-900 to-black border-4 border-red-700 rounded-2xl z-20"
                style={{ minHeight: 520 }}
              >
                <div className="text-white text-lg font-bold mb-2">Lore</div>
                <div className="text-white text-base px-4 text-center">
                  {card.lore || "No lore provided."}
                </div>
              </div>
            )}
          </div>
          {showCollection && (
            <div className="w-full max-w-2xl bg-gray-900 border border-red-700 rounded-lg p-4 mt-4">
              <div className="text-white font-bold mb-2 text-lg">
                Your Card Collection
              </div>
              <div className="flex flex-wrap gap-4">
                {collection.length === 0 && (
                  <div className="text-red-400">No cards saved yet.</div>
                )}
                {collection.map((c, i) => (
                  <div key={i} className="w-60">
                    <CharacterCard {...c} showRarityLabel />
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </main>
  );
}
