import {
  executeImageGeneration,
  imageGenerationTool,
} from "@/backend/lib/image-generation-tool";
import { MANGA_AI_SYSTEM_PROMPT } from "@/backend/lib/manga-system-prompt";
import { dataService } from "@/backend/services/data-service";
import { mcpClient } from "@/backend/services/mcp-client";
import { NextRequest, NextResponse } from "next/server";

interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: string;
  type?: "text" | "image";
  imageUrl?: string;
  imageData?: string;
  projectId: string;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      projectId,
      message,
      imageData,
      selectedMcpTools = [],
      userId,
    } = body;

    if (!projectId || !userId) {
      return NextResponse.json(
        { error: "Project ID and User ID are required" },
        { status: 400 }
      );
    }

    if (!message && !imageData) {
      return NextResponse.json(
        { error: "Message or image data is required" },
        { status: 400 }
      );
    }

    // Check if user exists and has credits (skip for anonymous users)
    let userProfile = null;
    if (userId !== "anonymous") {
      console.log("Chat API: Looking for user:", userId);
      try {
        userProfile = await dataService.getUserById(userId);
        console.log("Chat API: User found:", userProfile ? "YES" : "NO");
        if (userProfile) {
          console.log("Chat API: User credits:", userProfile.credits);
        }
      } catch (error) {
        console.error("Chat API: Error getting user:", error);
        return NextResponse.json(
          { error: "Error fetching user" },
          { status: 500 }
        );
      }

      if (!userProfile) {
        return NextResponse.json({ error: "User not found" }, { status: 404 });
      }

      if (userProfile.credits <= 0) {
        return NextResponse.json(
          { error: "Insufficient credits" },
          { status: 402 }
        );
      }
    }

    // Save user message to database
    const userMessage: ChatMessage = {
      id: "", // Will be auto-generated by database
      role: "user",
      content: message || "Image uploaded",
      timestamp: new Date().toISOString(),
      type: imageData ? "image" : "text",
      imageData: imageData || undefined,
      projectId,
    };

    await dataService.createChatMessage({
      // Don't pass ID, let database auto-generate UUID
      projectId: userMessage.projectId,
      userId,
      role: userMessage.role,
      content: userMessage.content,
      timestamp: userMessage.timestamp,
      messageType: userMessage.type,
      imageData: userMessage.imageData,
    });

    // Get recent conversation context (last 10 messages)
    const recentMessages = await dataService.getRecentChatMessages(
      projectId,
      10
    );

    // Prepare AI messages with context
    const geminiMessages = [
      ...recentMessages.map((m: any) => {
        if (m.type === "image" && m.imageData) {
          return {
            role: m.role as "user" | "assistant" | "function",
            content: [
              { text: m.content },
              {
                inlineData: {
                  mimeType: "image/jpeg",
                  data: m.imageData.split(",")[1], // Remove data:image/jpeg;base64, prefix
                },
              },
            ],
          };
        }
        return {
          role: m.role as "user" | "assistant" | "function",
          content: m.content,
        };
      }),
    ];

    // Prepare MCP tools
    let mcpTools: any[] = [];
    if (selectedMcpTools.length > 0) {
      // Get MCP tools from backend
      const availableTools = await mcpClient.getChatTools();
      mcpTools = availableTools
        .filter((tool) => selectedMcpTools.includes(tool.name))
        .map((tool) => ({
          name: tool.name,
          description: tool.description,
          parameters: tool.inputSchema,
        }));
    }

    // Always add image generation tool
    const allTools = [
      ...mcpTools,
      {
        name: imageGenerationTool.name,
        description: imageGenerationTool.description,
        parameters: imageGenerationTool.parameters,
      },
    ];

    // Use AI adapter directly instead of HTTP call
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "AI service not configured" },
        { status: 500 }
      );
    }

    // Get project details for enhanced context
    let projectInfo = "";
    try {
      const project = await dataService.getProject(projectId);
      if (project) {
        projectInfo = `
**Project Title**: ${project.title || "Untitled"}
**Description**: ${project.description || "No description available"}
**Genre**: ${project.genre || "Not specified"}
**Art Style**: ${project.artStyle || "Not specified"}
**Status**: ${project.status || "Unknown"}
**Target Audience**: ${project.targetAudience || "Not specified"}`;
      } else {
        projectInfo = `
**Note**: This appears to be a new project. Project details will be populated as you develop the manga.`;
      }
    } catch (error) {
      console.log("Could not fetch project details:", error);
      projectInfo = `
**Note**: Working with project ID ${projectId}. Project details will be loaded as available.`;
    }

    // Create enhanced system prompt with project context
    const enhancedSystemPrompt = `${MANGA_AI_SYSTEM_PROMPT}

## CURRENT PROJECT CONTEXT

**Project ID**: ${projectId}${projectInfo}

You are currently working on this specific manga project. All operations should be performed within this project context. When using MCP tools, always reference this project ID for creating or retrieving project-specific content like characters, scenes, chapters, outfits, and locations.

**Important**: Always include the project ID when calling MCP tools that require it, and ensure all creative work is associated with this specific project.`;

    const params = {
      model: "gemini-2.0-flash",
      systemPrompt: enhancedSystemPrompt,
      temperature: 0.7,
      maxOutputTokens: 8192,
      topP: 0.8,
      topK: 40,
    };

    // Import and use AI adapter directly
    const { ChatAdapterFactory } = await import(
      "@/backend/ai/adapters/factory"
    );
    const adapter = ChatAdapterFactory.getAdapter("gemini", apiKey);

    if (!adapter) {
      return NextResponse.json(
        { error: "AI adapter not available" },
        { status: 500 }
      );
    }

    const geminiResponses = await adapter.send(
      geminiMessages,
      allTools,
      params,
      false // callTool = false
    );

    // Process responses and handle tool calls
    let finalMessage = "";
    let generatedImageUrl: string | undefined;
    let totalTokensUsed = 0;
    let imagesGenerated = 0;
    let imageGenerationDetails: Array<{
      width: number;
      height: number;
      quality: string;
    }> = [];

    for (const response of geminiResponses) {
      if (response.role === "assistant") {
        const responseContent = response.content || "";
        finalMessage += responseContent;
        // Estimate tokens in response (rough: 4 characters per token)
        totalTokensUsed += Math.ceil(responseContent.length / 4);
      } else if (
        response.role === "function" &&
        response.contentKey === "functionCall"
      ) {
        const functionCall = response.content as {
          name: string;
          args: Record<string, any>;
        };

        if (functionCall.name === "generate_image") {
          try {
            const args = functionCall.args as {
              prompt: string;
              type: string;
              style?: string;
              entityId?: string;
              entityName?: string;
            };
            const result = await executeImageGeneration(args, {
              // Pass MCP actions mock for now
              updateEntity: async () => true,
            });
            if (result.success && result.imageUrl) {
              generatedImageUrl = result.imageUrl;
              imagesGenerated++;
              imageGenerationDetails.push({
                width: 1024,
                height: 1024,
                quality: "standard",
              });
              let statusMessage = `🎨 Generated ${args.type} image: ${args.prompt}`;
              if (result.entityUpdated) {
                statusMessage += ` ✅ Entity updated with image URL`;
              }
              finalMessage += `\n\n${statusMessage}`;
            } else {
              finalMessage += `\n\n❌ Image generation failed: ${result.error}`;
            }
          } catch (error: any) {
            console.error("Image generation error:", error);
            finalMessage += `\n\n❌ Image generation error: ${error.message}`;
          }
        }
        // Handle other MCP tool calls here if needed
      }
    }

    // Deduct credits based on actual usage
    let totalCreditsUsed = 0;
    const creditTransactions: Array<{
      operation: "textGeneration" | "imageGeneration";
      params: any;
      cost: number;
      description: string;
    }> = [];

    // 1. Deduct credits for text generation
    if (totalTokensUsed > 0) {
      const textCost = Math.ceil(totalTokensUsed / 1000); // 1 credit per 1000 tokens
      totalCreditsUsed += textCost;
      creditTransactions.push({
        operation: "textGeneration",
        params: { tokens: totalTokensUsed },
        cost: textCost,
        description: `Text generation (${totalTokensUsed} tokens)`,
      });
    }

    // 2. Deduct credits for image generation
    if (imagesGenerated > 0) {
      for (const imageDetail of imageGenerationDetails) {
        const imageCost = 10; // 10 credits per image
        totalCreditsUsed += imageCost;
        creditTransactions.push({
          operation: "imageGeneration",
          params: imageDetail,
          cost: imageCost,
          description: `Image generation (${imageDetail.width}x${imageDetail.height}, ${imageDetail.quality})`,
        });
      }
    }

    // Update user credits (skip for anonymous users)
    if (totalCreditsUsed > 0 && userId !== "anonymous" && userProfile) {
      await dataService.updateUserCredits(
        userId,
        userProfile.credits - totalCreditsUsed
      );

      // Log credit transaction
      await dataService.createCreditTransaction({
        // Don't pass ID, let database auto-generate UUID
        userId,
        type: "generation",
        amount: -totalCreditsUsed,
        operation: "text_generation",
        description: `Chat AI usage: ${creditTransactions
          .map((t) => t.description)
          .join(", ")}`,
      });
    }

    // Add credit usage summary to response (moved to avoid duplicates)
    // Credit summary will be added separately if needed

    // Save AI response to database
    const aiMessage: ChatMessage = {
      id: "", // Will be auto-generated by database
      role: "assistant",
      content: finalMessage || "I processed your request.",
      timestamp: new Date().toISOString(),
      type: generatedImageUrl ? "image" : "text",
      imageUrl: generatedImageUrl,
      projectId,
    };

    await dataService.createChatMessage({
      // Don't pass ID, let database auto-generate UUID
      projectId: aiMessage.projectId,
      userId,
      role: aiMessage.role,
      content: aiMessage.content,
      timestamp: aiMessage.timestamp,
      messageType: aiMessage.type,
      imageUrl: aiMessage.imageUrl,
    });

    return NextResponse.json({
      success: true,
      message: aiMessage,
      creditsUsed: totalCreditsUsed,
      remainingCredits: userProfile
        ? userProfile.credits - totalCreditsUsed
        : null,
    });
  } catch (error: any) {
    console.error("Chat API error:", error);
    return NextResponse.json(
      { error: "Failed to process chat message" },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const projectId = searchParams.get("projectId");
    const limit = parseInt(searchParams.get("limit") || "50");
    const offset = parseInt(searchParams.get("offset") || "0");

    if (!projectId) {
      return NextResponse.json(
        { error: "Project ID is required" },
        { status: 400 }
      );
    }

    // Get messages for the project
    const messages = await dataService.getChatMessages(projectId, {
      limit,
      offset,
    });

    return NextResponse.json({
      success: true,
      messages,
    });
  } catch (error: any) {
    console.error("Get messages API error:", error);
    return NextResponse.json(
      { error: "Failed to get messages" },
      { status: 500 }
    );
  }
}
