import {
  executeImageGeneration,
  imageGenerationTool,
} from "@/backend/lib/image-generation-tool";
import { MANGA_AI_SYSTEM_PROMPT } from "@/backend/lib/manga-system-prompt";
import { dataService } from "@/backend/services/data-service";
import { mcpClient } from "@/backend/services/mcp-client";
import { NextRequest, NextResponse } from "next/server";

interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: string;
  type?: "text" | "image";
  imageUrl?: string;
  imageData?: string;
  projectId: string;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      projectId,
      message,
      imageData,
      selectedMcpTools = [],
      userId,
    } = body;

    if (!projectId || !userId) {
      return NextResponse.json(
        { error: "Project ID and User ID are required" },
        { status: 400 }
      );
    }

    if (!message && !imageData) {
      return NextResponse.json(
        { error: "Message or image data is required" },
        { status: 400 }
      );
    }

    // Check if user exists and has credits (skip for anonymous users)
    let userProfile = null;
    if (userId !== "anonymous") {
      console.log("Chat API: Looking for user:", userId);
      try {
        userProfile = await dataService.getUserById(userId);
        console.log("Chat API: User found:", userProfile ? "YES" : "NO");
        if (userProfile) {
          console.log("Chat API: User credits:", userProfile.credits);
        }
      } catch (error) {
        console.error("Chat API: Error getting user:", error);
        return NextResponse.json(
          { error: "Error fetching user" },
          { status: 500 }
        );
      }

      if (!userProfile) {
        return NextResponse.json({ error: "User not found" }, { status: 404 });
      }

      if (userProfile.credits <= 0) {
        return NextResponse.json(
          { error: "Insufficient credits" },
          { status: 402 }
        );
      }
    }

    // Save user message to database
    const userMessage: ChatMessage = {
      id: "", // Will be auto-generated by database
      role: "user",
      content: message || "Image uploaded",
      timestamp: new Date().toISOString(),
      type: imageData ? "image" : "text",
      imageData: imageData || undefined,
      projectId,
    };

    await dataService.createChatMessage({
      // Don't pass ID, let database auto-generate UUID
      projectId: userMessage.projectId,
      userId,
      role: userMessage.role,
      content: userMessage.content,
      timestamp: userMessage.timestamp,
      messageType: userMessage.type,
      imageData: userMessage.imageData,
    });

    // Get recent conversation context (last 15 messages for better context)
    const recentMessages = await dataService.getRecentChatMessages(
      projectId,
      15 // Increased from 10 to provide more context for AI decisions
    );

    // Prepare AI messages with context
    const geminiMessages = [
      ...recentMessages.map((m: any) => {
        if (m.type === "image" && m.imageData) {
          return {
            role: m.role as "user" | "assistant" | "function",
            content: [
              { text: m.content },
              {
                inlineData: {
                  mimeType: "image/jpeg",
                  data: m.imageData.split(",")[1], // Remove data:image/jpeg;base64, prefix
                },
              },
            ],
          };
        }
        return {
          role: m.role as "user" | "assistant" | "function",
          content: m.content,
        };
      }),
    ];

    // AUTO-ENABLE ALL MCP TOOLS for beginners (they shouldn't need to select tools)
    const availableTools = await mcpClient.getChatTools();
    const mcpTools = availableTools
      .filter((tool) => selectedMcpTools.includes(tool.name))
      .map((tool) => ({
        name: tool.name,
        description: tool.description,
        parameters: tool.inputSchema,
      }));

    // Always add image generation tool
    const allTools = [
      ...mcpTools,
      {
        name: imageGenerationTool.name,
        description: imageGenerationTool.description,
        parameters: imageGenerationTool.parameters,
      },
    ];

    // Use AI adapter directly instead of HTTP call
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "AI service not configured" },
        { status: 500 }
      );
    }

    // Get COMPREHENSIVE project details for enhanced context
    let projectInfo = "";
    let fullProjectContext = "";
    try {
      const project = await dataService.getProject(projectId);
      if (project) {
        // Create rich project summary for AI context
        projectInfo = `
**Project Title**: ${project.title || "Untitled Manga"}
**Description**: ${project.description || "No description available"}
**Genre**: ${project.genre || "Not specified"}
**Art Style**: ${project.artStyle || "Anime/Manga"}
**Status**: ${project.status || "In Development"}
**Target Audience**: ${project.targetAudience || "General"}

### STORY CONTEXT
${project.concept ? `**Concept**: ${project.concept}` : ""}
${
  project.themes && project.themes.length > 0
    ? `**Themes**: ${project.themes.join(", ")}`
    : ""
}
${
  project.plotStructure
    ? `
**Plot Structure**:
- Inciting Incident: ${
        project.plotStructure.incitingIncident || "To be developed"
      }
- Plot Twist: ${project.plotStructure.plotTwist || "To be developed"}
- Climax: ${project.plotStructure.climax || "To be developed"}
- Resolution: ${project.plotStructure.resolution || "To be developed"}`
    : ""
}

### EXISTING PROJECT CONTENT`;

        // Enhanced content overview with more detail
        const charactersInfo =
          project.characters && project.characters.length > 0
            ? project.characters
                .map((char) => {
                  const outfitInfo = char.defaultOutfitId
                    ? ` [Default Outfit: ${char.defaultOutfitId}]`
                    : "";
                  const personalityInfo = char.personality
                    ? ` - ${char.personality.substring(0, 50)}${
                        char.personality.length > 50 ? "..." : ""
                      }`
                    : "";
                  return `├── ${char.name} (${char.id}) - ${
                    char.role || "minor"
                  }${outfitInfo}${personalityInfo}`;
                })
                .join("\n")
            : "└── No characters created yet - Consider creating main characters first";

        const outfitsInfo =
          project.outfitTemplates && project.outfitTemplates.length > 0
            ? project.outfitTemplates
                .map(
                  (outfit) =>
                    `├── ${outfit.name} (${outfit.id}) - ${outfit.category}`
                )
                .join("\n")
            : "└── No outfit templates - Characters will need outfits for scenes";

        const locationsInfo =
          project.locationTemplates && project.locationTemplates.length > 0
            ? project.locationTemplates
                .map(
                  (location) =>
                    `├── ${location.name} (${location.id}) - ${location.category}`
                )
                .join("\n")
            : "└── No locations created - Stories need settings and backgrounds";

        const chaptersInfo =
          project.chapters && project.chapters.length > 0
            ? project.chapters
                .map((chapter) => {
                  const sceneCount = chapter.scenes ? chapter.scenes.length : 0;
                  const totalPanels = chapter.scenes
                    ? chapter.scenes.reduce(
                        (acc, scene) =>
                          acc + (scene.panels ? scene.panels.length : 0),
                        0
                      )
                    : 0;
                  return `├── Chapter ${chapter.chapterNumber}: "${chapter.title}" (${chapter.id}) - ${sceneCount} scenes, ${totalPanels} panels`;
                })
                .join("\n")
            : "└── No chapters created - Start with Chapter 1 to begin the story";

        fullProjectContext = `
📚 **Characters**: ${project.characters ? project.characters.length : 0} total
${charactersInfo}

👕 **Outfit Templates**: ${
          project.outfitTemplates ? project.outfitTemplates.length : 0
        } total
${outfitsInfo}

🏛️ **Location Templates**: ${
          project.locationTemplates ? project.locationTemplates.length : 0
        } total
${locationsInfo}

📖 **Chapters**: ${project.chapters ? project.chapters.length : 0} total
${chaptersInfo}`;

        // Add project analysis for AI decision making
        const analysisInfo = `

### PROJECT ANALYSIS FOR AI DECISIONS
**Current Stage**: ${
          !project.characters || project.characters.length === 0
            ? "Character Creation Needed"
            : !project.locationTemplates ||
              project.locationTemplates.length === 0
            ? "Location Setup Needed"
            : !project.outfitTemplates || project.outfitTemplates.length === 0
            ? "Outfit Templates Needed"
            : !project.chapters || project.chapters.length === 0
            ? "Story Development Ready"
            : "Content Expansion Phase"
        }

**Next Logical Steps**:
${
  !project.characters || project.characters.length === 0
    ? "- Create main characters (protagonist, supporting characters)"
    : ""
}
${
  !project.locationTemplates || project.locationTemplates.length === 0
    ? "- Design key locations where story takes place"
    : ""
}
${
  !project.outfitTemplates || project.outfitTemplates.length === 0
    ? "- Create outfit templates for different characters and situations"
    : ""
}
${
  !project.chapters || project.chapters.length === 0
    ? "- Begin Chapter 1 with character introductions"
    : ""
}
${
  project.chapters && project.chapters.length > 0
    ? "- Expand existing chapters with more scenes and panels"
    : ""
}

**Story Development Opportunities**:
${
  project.characters && project.characters.length > 0
    ? `- Character interactions between ${project.characters
        .map((c) => c.name)
        .join(", ")}`
    : ""
}
${
  project.locationTemplates && project.locationTemplates.length > 0
    ? `- Utilize created locations: ${project.locationTemplates
        .map((l) => l.name)
        .join(", ")}`
    : ""
}
${
  project.plotStructure
    ? "- Develop established plot points further"
    : "- Establish clear story structure"
}`;

        projectInfo += fullProjectContext + analysisInfo;
      } else {
        projectInfo = `
**Note**: This appears to be a new project. I'll help you build it from the ground up, starting with characters and basic story elements.

### GETTING STARTED RECOMMENDATIONS
Since this is a new project, I suggest we begin with:
1. **Main Characters** - Create your protagonist and key supporting characters
2. **Core Locations** - Design the primary settings where your story takes place  
3. **Outfit Templates** - Create clothing options for different characters and situations
4. **Chapter 1** - Begin the story with character introductions and world-building`;
      }
    } catch (error) {
      console.log("Could not fetch project details:", error);
      projectInfo = `
**Note**: Working with project ID ${projectId}. I'll help you develop this manga project step by step.`;
    }

    // Enhanced system prompt with current project context
    const enhancedSystemPrompt = `${MANGA_AI_SYSTEM_PROMPT}

## CURRENT PROJECT CONTEXT

**Project ID**: ${projectId}${projectInfo}

You are currently working on this specific manga project. All operations should be performed within this project context, using the established workflow and content creation standards defined above.`;

    // Adjust AI parameters for more creative and autonomous generation
    const params = {
      model: "gemini-2.0-flash",
      systemPrompt: enhancedSystemPrompt,
      temperature: 0.8, // Increased for more creativity
      maxOutputTokens: 8192,
      topP: 0.85, // Slightly increased for more varied responses
      topK: 50, // Increased for more creative word choices
    };

    // Import and use AI adapter directly
    const { ChatAdapterFactory } = await import(
      "@/backend/ai/adapters/factory"
    );
    const adapter = ChatAdapterFactory.getAdapter("gemini", apiKey);

    if (!adapter) {
      return NextResponse.json(
        { error: "AI adapter not available" },
        { status: 500 }
      );
    }

    const geminiResponses = await adapter.send(
      geminiMessages,
      allTools,
      params,
      false // callTool = false
    );

    // Process responses and handle tool calls
    let finalMessage = "";
    let generatedImageUrl: string | undefined;
    let totalTokensUsed = 0;
    let imagesGenerated = 0;
    let imageGenerationDetails: Array<{
      width: number;
      height: number;
      quality: string;
    }> = [];

    for (const response of geminiResponses) {
      if (response.role === "assistant") {
        const responseContent = response.content || "";
        finalMessage += responseContent;
        // Estimate tokens in response (rough: 4 characters per token)
        totalTokensUsed += Math.ceil(responseContent.length / 4);
      } else if (
        response.role === "function" &&
        response.contentKey === "functionCall"
      ) {
        const functionCall = response.content as {
          name: string;
          args: Record<string, any>;
        };

        if (functionCall.name === "generate_image") {
          try {
            const args = functionCall.args as {
              prompt: string;
              type: string;
              style?: string;
              entityId?: string;
              entityName?: string;
            };
            const result = await executeImageGeneration(args, {
              // Pass MCP actions mock for now
              updateEntity: async () => true,
            });
            if (result.success && result.imageUrl) {
              generatedImageUrl = result.imageUrl;
              imagesGenerated++;
              imageGenerationDetails.push({
                width: 1024,
                height: 1024,
                quality: "standard",
              });
              let statusMessage = `🎨 Generated ${args.type} image: ${args.prompt}`;
              if (result.entityUpdated) {
                statusMessage += ` ✅ Entity updated with image URL`;
              }
              finalMessage += `\n\n${statusMessage}`;
            } else {
              finalMessage += `\n\n❌ Image generation failed: ${result.error}`;
            }
          } catch (error: any) {
            console.error("Image generation error:", error);
            finalMessage += `\n\n❌ Image generation error: ${error.message}`;
          }
        }
        // Handle other MCP tool calls here if needed
      }
    }

    // Enhanced tool call extraction and execution with better error handling
    const extractAndExecuteTextToolCalls = async (
      text: string
    ): Promise<{ cleanedText: string; toolResults: string[] }> => {
      const toolResults: string[] = [];
      let cleanedText = text;

      // Pattern 1: Regular expression to match tool_code blocks
      const toolCodeRegex = /```tool_code\s*\n([\s\S]*?)\n```/g;
      const codeBlockMatches = [...text.matchAll(toolCodeRegex)];

      // Pattern 2: Direct print(default_api. calls (not in code blocks)
      const directCallRegex = /print\(default_api\.(\w+)\(([\s\S]*?)\)\)/g;
      const directMatches = [...text.matchAll(directCallRegex)];

      // Process code block matches first
      for (const match of codeBlockMatches) {
        const toolCode = match[1].trim();

        try {
          // Extract function name and parameters from the tool code
          const functionCallRegex = /print\(default_api\.(\w+)\(([\s\S]*?)\)\)/;
          const functionMatch = toolCode.match(functionCallRegex);

          if (functionMatch) {
            const functionName = functionMatch[1];
            const parametersString = functionMatch[2];

            const params = await parseToolParameters(parametersString);

            console.log(
              `🔧 Executing tool call from code block: ${functionName} with params:`,
              params
            );

            try {
              const toolResult = await mcpClient.callTool(functionName, params);

              // Enhanced success feedback for different tool types
              let successMessage = "";
              if (functionName.includes("create")) {
                successMessage = `✅ Created ${functionName
                  .replace("create", "")
                  .toLowerCase()}: ${JSON.stringify(toolResult)}`;
              } else if (functionName.includes("list")) {
                const count = Array.isArray(toolResult)
                  ? toolResult.length
                  : "multiple";
                successMessage = `📋 Listed ${count} ${functionName
                  .replace("list", "")
                  .toLowerCase()}(s)`;
              } else if (functionName.includes("get")) {
                successMessage = `📄 Retrieved ${functionName
                  .replace("get", "")
                  .toLowerCase()} details`;
              } else {
                successMessage = `✅ ${functionName} executed successfully`;
              }

              toolResults.push(successMessage);
              console.log(
                `✅ Tool ${functionName} executed successfully:`,
                toolResult
              );
            } catch (error: any) {
              const errorMsg = `❌ Tool ${functionName} failed: ${error.message}`;
              toolResults.push(errorMsg);
              console.error("Tool execution error:", error);
            }
          }
        } catch (error: any) {
          console.error("Error parsing tool code:", error);
          toolResults.push(`❌ Failed to parse tool call: ${error.message}`);
        }

        // Remove the tool_code block from the message
        cleanedText = cleanedText.replace(match[0], "");
      }

      // Process direct print() calls (same logic as before)
      for (const match of directMatches) {
        // Skip if this match was already processed in a code block
        let isInCodeBlock = false;
        for (const codeMatch of codeBlockMatches) {
          if (codeMatch[0].includes(match[0])) {
            isInCodeBlock = true;
            break;
          }
        }
        if (isInCodeBlock) continue;

        try {
          const functionName = match[1];
          const parametersString = match[2];

          const params = await parseToolParameters(parametersString);

          console.log(
            `🔧 Executing direct tool call: ${functionName} with params:`,
            params
          );

          try {
            const toolResult = await mcpClient.callTool(functionName, params);

            // Enhanced success feedback
            let successMessage = "";
            if (functionName.includes("create")) {
              successMessage = `✅ Created ${functionName
                .replace("create", "")
                .toLowerCase()}`;
            } else if (functionName.includes("list")) {
              const count = Array.isArray(toolResult)
                ? toolResult.length
                : "multiple";
              successMessage = `📋 Found ${count} ${functionName
                .replace("list", "")
                .toLowerCase()}(s)`;
            } else {
              successMessage = `✅ ${functionName} completed`;
            }

            toolResults.push(successMessage);
            console.log(
              `✅ Tool ${functionName} executed successfully:`,
              toolResult
            );
          } catch (error: any) {
            const errorMsg = `❌ Tool ${functionName} failed: ${error.message}`;
            toolResults.push(errorMsg);
            console.error("Tool execution error:", error);
          }
        } catch (error: any) {
          console.error("Error parsing direct tool call:", error);
          toolResults.push(`❌ Failed to parse tool call: ${error.message}`);
        }

        // Remove the direct print() call from the message
        cleanedText = cleanedText.replace(match[0], "");
      }

      // Clean up extra whitespace
      cleanedText = cleanedText.replace(/\n\s*\n\s*\n/g, "\n\n").trim();

      return { cleanedText, toolResults };
    };

    // Helper function to parse tool parameters (unchanged)
    const parseToolParameters = async (
      parametersString: string
    ): Promise<Record<string, any>> => {
      const params: Record<string, any> = {};

      // Handle different parameter formats
      if (parametersString.trim()) {
        // Split by comma but respect quoted strings and arrays
        const paramPairs = parametersString.split(
          /,(?=(?:[^"]*"[^"]*")*[^"]*$)/
        );

        for (const pair of paramPairs) {
          const [key, ...valueParts] = pair.split("=");
          if (key && valueParts.length > 0) {
            const cleanKey = key.trim();
            let value = valueParts.join("=").trim();

            // Remove surrounding quotes
            if (
              (value.startsWith('"') && value.endsWith('"')) ||
              (value.startsWith("'") && value.endsWith("'"))
            ) {
              value = value.slice(1, -1);
            }

            // Handle arrays (basic JSON parsing)
            if (value.startsWith("[") && value.endsWith("]")) {
              try {
                value = JSON.parse(value);
              } catch (e) {
                console.warn("Failed to parse array parameter:", value);
              }
            }

            params[cleanKey] = value;
          }
        }
      }

      return params;
    };

    // Process text-based tool calls if any
    if (
      finalMessage.includes("```tool_code") ||
      finalMessage.includes("print(default_api.")
    ) {
      const { cleanedText, toolResults } = await extractAndExecuteTextToolCalls(
        finalMessage
      );
      finalMessage = cleanedText;

      // Add tool execution results to the message with better formatting
      if (toolResults.length > 0) {
        finalMessage += "\n\n**Actions Completed:**\n" + toolResults.join("\n");
      }
    }

    // Deduct credits based on actual usage (unchanged)
    let totalCreditsUsed = 0;
    const creditTransactions: Array<{
      operation: "textGeneration" | "imageGeneration";
      params: any;
      cost: number;
      description: string;
    }> = [];

    // 1. Deduct credits for text generation
    if (totalTokensUsed > 0) {
      const textCost = Math.ceil(totalTokensUsed / 1000); // 1 credit per 1000 tokens
      totalCreditsUsed += textCost;
      creditTransactions.push({
        operation: "textGeneration",
        params: { tokens: totalTokensUsed },
        cost: textCost,
        description: `Text generation (${totalTokensUsed} tokens)`,
      });
    }

    // 2. Deduct credits for image generation
    if (imagesGenerated > 0) {
      for (const imageDetail of imageGenerationDetails) {
        const imageCost = 10; // 10 credits per image
        totalCreditsUsed += imageCost;
        creditTransactions.push({
          operation: "imageGeneration",
          params: imageDetail,
          cost: imageCost,
          description: `Image generation (${imageDetail.width}x${imageDetail.height}, ${imageDetail.quality})`,
        });
      }
    }

    // Update user credits (skip for anonymous users)
    if (totalCreditsUsed > 0 && userId !== "anonymous" && userProfile) {
      await dataService.updateUserCredits(
        userId,
        userProfile.credits - totalCreditsUsed
      );

      // Log credit transaction
      await dataService.createCreditTransaction({
        // Don't pass ID, let database auto-generate UUID
        userId,
        type: "generation",
        amount: -totalCreditsUsed,
        operation: "text_generation",
        description: `AI Manga Creation: ${creditTransactions
          .map((t) => t.description)
          .join(", ")}`,
      });
    }

    // Save AI response to database
    const aiMessage: ChatMessage = {
      id: "", // Will be auto-generated by database
      role: "assistant",
      content:
        finalMessage || "I've processed your request and created the content.",
      timestamp: new Date().toISOString(),
      type: generatedImageUrl ? "image" : "text",
      imageUrl: generatedImageUrl,
      projectId,
    };

    await dataService.createChatMessage({
      // Don't pass ID, let database auto-generate UUID
      projectId: aiMessage.projectId,
      userId,
      role: aiMessage.role,
      content: aiMessage.content,
      timestamp: aiMessage.timestamp,
      messageType: aiMessage.type,
      imageUrl: aiMessage.imageUrl,
    });

    return NextResponse.json({
      success: true,
      message: aiMessage,
      creditsUsed: totalCreditsUsed,
      remainingCredits: userProfile
        ? userProfile.credits - totalCreditsUsed
        : null,
    });
  } catch (error: any) {
    console.error("Chat API error:", error);
    return NextResponse.json(
      { error: "Failed to process chat message" },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const projectId = searchParams.get("projectId");
    const limit = parseInt(searchParams.get("limit") || "50");
    const offset = parseInt(searchParams.get("offset") || "0");

    if (!projectId) {
      return NextResponse.json(
        { error: "Project ID is required" },
        { status: 400 }
      );
    }

    // Get messages for the project
    const messages = await dataService.getChatMessages(projectId, {
      limit,
      offset,
    });

    return NextResponse.json({
      success: true,
      messages,
    });
  } catch (error: any) {
    console.error("Get messages API error:", error);
    return NextResponse.json(
      { error: "Failed to get messages" },
      { status: 500 }
    );
  }
}
